# -*- coding: utf-8 -*-
"""
Genereert assets/data/handbooks.json en assets/data/rules.json op basis van de
twaalf handboeken die daadwerkelijk bestaan (zes families x Core/Pro).

Paginaaantallen, ondertitels en hoofdstukken komen uit de PDF's zelf.
Draaien:  python3 tools/make_handbooks.py
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PRICE_CORE, PRICE_PRO = 39, 79

FAMILIES = {
    "power":     {"label": {"nl": "Explosiviteit", "en": "Power", "de": "Explosivität"},   "accent": "#7ec8ff"},
    "strength":  {"label": {"nl": "Kracht", "en": "Strength", "de": "Kraft"},              "accent": "#7ec8ff"},
    "speed":     {"label": {"nl": "Snelheid", "en": "Speed", "de": "Schnelligkeit"},       "accent": "#7ec8ff"},
    "agility":   {"label": {"nl": "Agility", "en": "Agility", "de": "Agilität"},           "accent": "#7ec8ff"},
    "season":    {"label": {"nl": "In het seizoen", "en": "In season", "de": "In der Saison"}, "accent": "#7ec8ff"},
    "preseason": {"label": {"nl": "Voorbereiding", "en": "Pre-season", "de": "Vorbereitung"},  "accent": "#7ec8ff"},
}

# family, version -> alle inhoud
BOOKS = [
# ---------------------------------------------------------------- POWER core
dict(id="power-foundations-core", family="power", version="core", nr="01",
 pages=60, weeks=12, category="strength", phase=["off-season", "pre-season", "power"],
 recommendFor=["elastic:below", "rfd:below"], featured=True,
 badges={"nl": ["12 weken", "Core", "60 pagina's"], "en": ["12 weeks", "Core", "60 pages"], "de": ["12 Wochen", "Core", "60 Seiten"]},
 title={"nl": "Power Foundations — Core", "en": "Power Foundations — Core", "de": "Power Foundations — Core"},
 tagline={"nl": "Explosiviteit begrijpen, meten en systematisch opbouwen.",
          "en": "Understand, measure and systematically build explosiveness.",
          "de": "Explosivität verstehen, messen und systematisch aufbauen."},
 summary={"nl": "Voor sporters die sterker worden zonder sneller te worden. Twintig hoofdstukken over hoe explosiviteit werkelijk tot stand komt — force-velocity, rate of force development, de stretch-shortening cycle — plus vijf methoden, een testbatterij en drie twaalf-weken programma's waaruit je er één kiest op basis van je eigen meting.",
          "en": "For athletes who get stronger without getting faster. Twenty chapters on how explosiveness actually works — force-velocity, rate of force development, the stretch-shortening cycle — plus five methods, a test battery and three twelve-week programmes you pick from based on your own measurement.",
          "de": "Für Sportler, die stärker werden, ohne schneller zu werden. Zwanzig Kapitel darüber, wie Explosivität wirklich entsteht — Force-Velocity, Rate of Force Development, der Dehnungs-Verkürzungs-Zyklus — dazu fünf Methoden, eine Testbatterie und drei Zwölf-Wochen-Programme, aus denen du auf Basis deiner eigenen Messung wählst."},
 audience={"nl": "Sporters die al met gewichten trainen en willen begrijpen waarom hun kracht niet automatisch snelheid wordt.",
           "en": "Athletes already lifting who want to understand why their strength does not automatically become speed.",
           "de": "Sportler, die bereits mit Gewichten trainieren und verstehen wollen, warum ihre Kraft nicht automatisch zu Schnelligkeit wird."},
 learn={"nl": ["Waarom je maximale kracht zelden beschikbaar is in de tijd die je sport je geeft",
               "Hoe je met vier veldtests bepaalt of je een kracht-, omzettings- of reactief probleem hebt",
               "Welke van de vijf methoden bij jouw profiel hoort, via een beslisboom",
               "Hoe je explosief werk plant zonder het weg te trainen met volume"],
        "en": ["Why your maximal strength is rarely available in the time your sport gives you",
               "How four field tests tell you whether you have a strength, conversion or reactive problem",
               "Which of the five methods fits your profile, via a decision tree",
               "How to programme explosive work without training it away with volume"],
        "de": ["Warum deine Maximalkraft in der verfügbaren Zeit selten abrufbar ist",
               "Wie vier Feldtests zeigen, ob du ein Kraft-, Umsetzungs- oder reaktives Problem hast",
               "Welche der fünf Methoden zu deinem Profil passt — über einen Entscheidungsbaum",
               "Wie du explosive Arbeit planst, ohne sie mit Volumen wegzutrainieren"]},
 contents={"nl": ["Deel I — Het model: force-velocity, RFD en de transferwet",
                  "Deel II — De methoden: zwaar, ballistisch, plyometrie, sprint, rotatie",
                  "Deel III — Het programma: variabelen, week, jaar, herstel",
                  "De drie twaalf-weken programma's",
                  "Bijlagen: oefenbibliotheek, testprotocollen, logboek, de twintig fouten"],
           "en": ["Part I — The model: force-velocity, RFD and the transfer law",
                  "Part II — The methods: heavy, ballistic, plyometrics, sprinting, rotation",
                  "Part III — The programme: variables, week, year, recovery",
                  "The three twelve-week programmes",
                  "Appendices: exercise library, test protocols, logbook, the twenty mistakes"],
           "de": ["Teil I — Das Modell: Force-Velocity, RFD und das Transfergesetz",
                  "Teil II — Die Methoden: schwer, ballistisch, Plyometrie, Sprint, Rotation",
                  "Teil III — Das Programm: Variablen, Woche, Jahr, Erholung",
                  "Die drei Zwölf-Wochen-Programme",
                  "Anhänge: Übungsbibliothek, Testprotokolle, Logbuch, die zwanzig Fehler"]},
 teaserQuote={"nl": "Kracht is capaciteit. Power is wat je ermee doet in de honderdvijftig milliseconden die je hebt.",
              "en": "Strength is capacity. Power is what you do with it in the hundred and fifty milliseconds you get.",
              "de": "Kraft ist Kapazität. Power ist das, was du in den hundertfünfzig Millisekunden daraus machst."}),
# ----------------------------------------------------------------- POWER pro
dict(id="power-foundations-pro", family="power", version="pro", nr="01",
 pages=59, weeks=8, category="strength", phase=["off-season", "pre-season", "season", "power"],
 recommendFor=["elastic:below", "rfd:below"], featured=False,
 badges={"nl": ["Pro", "IJshockey", "59 pagina's"], "en": ["Pro", "Ice hockey", "59 pages"], "de": ["Pro", "Eishockey", "59 Seiten"]},
 title={"nl": "Power Foundations — Pro", "en": "Power Foundations — Pro", "de": "Power Foundations — Pro"},
 tagline={"nl": "Explosiviteit vertaald naar het ijs, en naar twee tot drie wedstrijden per week.",
          "en": "Explosiveness translated to the ice, and to two or three games a week.",
          "de": "Explosivität übersetzt aufs Eis — und auf zwei bis drei Spiele pro Woche."},
 summary={"nl": "Bouwt voort op de Core Edition en herhaalt de basis niet. De biomechanica van de schaatsafzet, waarom je programma vaak het verkeerde vlak traint, de ontbrekende excentrische prikkel, en een volledig in-season model van twee sessies per week. Met zes bonusmodules, waaronder een gameday-protocol en een keeperbijlage.",
          "en": "Builds on the Core Edition and does not repeat the basics. The biomechanics of the skating stride, why your programme often trains the wrong plane, the missing eccentric stimulus, and a full in-season model of two sessions a week. Includes six bonus modules, among them a gameday protocol and a goalie appendix.",
          "de": "Baut auf der Core Edition auf und wiederholt die Grundlagen nicht. Die Biomechanik des Schrittabstoßes, warum dein Programm oft die falsche Ebene trainiert, der fehlende exzentrische Reiz und ein vollständiges In-Season-Modell mit zwei Einheiten pro Woche. Mit sechs Bonusmodulen, darunter Gameday-Protokoll und Torwart-Anhang."},
 audience={"nl": "IJshockeyers en staf die de Core kennen en willen weten hoe het binnen een seizoenskalender past.",
           "en": "Ice hockey players and staff who know the Core and want to know how it fits a season calendar.",
           "de": "Eishockeyspieler und Staff, die die Core kennen und wissen wollen, wie sie in einen Saisonkalender passt."},
 learn={"nl": ["Waarom de schaatsafzet niet in het sagittale vlak plaatsvindt, en wat dat voor je oefenselectie betekent",
               "Hoe je off-ice de excentrische prikkel terugbrengt die het ijs zeven maanden niet geeft",
               "Het in-season model van twee sessies per week, ook in weken met drie wedstrijden",
               "Hoe je heup en lies monitort als prestatie- én blessurevariabele"],
        "en": ["Why the skating stride does not happen in the sagittal plane, and what that means for exercise selection",
               "How to restore off-ice the eccentric stimulus the ice does not provide for seven months",
               "The in-season model of two sessions a week, including weeks with three games",
               "How to monitor hip and groin as both a performance and an injury variable"],
        "de": ["Warum der Schlittschuhabstoß nicht in der Sagittalebene stattfindet — und was das für die Übungsauswahl bedeutet",
               "Wie du off-ice den exzentrischen Reiz zurückbringst, den das Eis sieben Monate lang nicht gibt",
               "Das In-Season-Modell mit zwei Einheiten pro Woche, auch in Wochen mit drei Spielen",
               "Wie du Hüfte und Leiste als Leistungs- und Verletzungsvariable überwachst"]},
 contents={"nl": ["Deel I — De sport ontleed: shifts, schaatsafzet, acceleratie versus topsnelheid",
                  "Deel II — De aanpassingen: oefenselectie, diepe hoeken, heup en lies",
                  "Deel III — Het seizoen: off-season, voorbereiding, in-season, gameday",
                  "Deel IV — Positieaccenten, jeugdpad en terugkeer na blessure",
                  "Bonusmodules: on-ice en off-ice testbatterij, 20-minutenprotocol, keeperbijlage"],
           "en": ["Part I — The sport dissected: shifts, skating stride, acceleration versus top speed",
                  "Part II — The adjustments: exercise selection, deep angles, hip and groin",
                  "Part III — The season: off-season, pre-season, in-season, gameday",
                  "Part IV — Positional accents, youth pathway and return after injury",
                  "Bonus modules: on-ice and off-ice test battery, 20-minute protocol, goalie appendix"],
           "de": ["Teil I — Die Sportart seziert: Shifts, Schlittschuhabstoß, Beschleunigung versus Höchstgeschwindigkeit",
                  "Teil II — Die Anpassungen: Übungsauswahl, tiefe Winkel, Hüfte und Leiste",
                  "Teil III — Die Saison: Off-Season, Vorbereitung, In-Season, Gameday",
                  "Teil IV — Positionsakzente, Jugendweg und Rückkehr nach Verletzung",
                  "Bonusmodule: On-Ice- und Off-Ice-Testbatterie, 20-Minuten-Protokoll, Torwart-Anhang"]},
 teaserQuote={"nl": "Op het ijs word je nauwelijks geremd. Wat het ijs je niet geeft, moet je er zelf naast zetten.",
              "en": "On the ice you are barely braked. What the ice does not give you, you have to add yourself.",
              "de": "Auf dem Eis wirst du kaum gebremst. Was das Eis dir nicht gibt, musst du selbst danebenstellen."}),
# ------------------------------------------------------------- STRENGTH core
dict(id="strength-foundations-core", family="strength", version="core", nr="02",
 pages=57, weeks=12, category="strength", phase=["off-season", "pre-season", "power"],
 recommendFor=["strength:below", "asymmetry:yes"], featured=True,
 badges={"nl": ["12 weken", "Core", "57 pagina's"], "en": ["12 weeks", "Core", "57 pages"], "de": ["12 Wochen", "Core", "57 Seiten"]},
 title={"nl": "Strength Foundations — Core", "en": "Strength Foundations — Core", "de": "Strength Foundations — Core"},
 tagline={"nl": "Sterker worden met een doel: beter presteren in je sport.",
          "en": "Getting stronger with a purpose: performing better in your sport.",
          "de": "Stärker werden mit einem Ziel: in deinem Sport besser leisten."},
 summary={"nl": "Hoe kracht werkelijk ontstaat en hoe je hem stuurt. Belasting, volume, nabijheid tot falen, frequentie, tempo en de zes wegen van progressive overload — plus autoregulatie voor de dagen waarop het niet loopt. Met drie twaalf-weken programma's en een testmethode die geen 1RM vraagt.",
          "en": "How strength actually develops and how you steer it. Load, volume, proximity to failure, frequency, tempo and the six routes to progressive overload — plus autoregulation for the days it does not go to plan. With three twelve-week programmes and a testing method that needs no 1RM.",
          "de": "Wie Kraft wirklich entsteht und wie du sie steuerst. Last, Volumen, Nähe zum Muskelversagen, Frequenz, Tempo und die sechs Wege der progressiven Überlastung — dazu Autoregulation für Tage, an denen es nicht läuft. Mit drei Zwölf-Wochen-Programmen und einer Testmethode ohne 1RM."},
 audience={"nl": "Sporters onder de referentiewaarde voor kracht, en iedereen die zijn programma wil kunnen verdedigen in plaats van kopiëren.",
           "en": "Athletes below the strength reference range, and anyone who wants to defend their programme rather than copy it.",
           "de": "Sportler unter dem Kraft-Referenzbereich und alle, die ihr Programm begründen statt kopieren wollen."},
 learn={"nl": ["Waar krachtwinst vandaan komt en wat er in welke week verandert",
               "Hoeveel volume genoeg is, en hoe dicht bij falen je werkelijk moet trainen",
               "De zes wegen van progressive overload als je gewicht niet omhoog kan",
               "Hoe je kracht test zonder ooit een 1RM te hoeven doen"],
        "en": ["Where strength gains come from and what changes in which week",
               "How much volume is enough, and how close to failure you actually need to train",
               "The six routes to progressive overload when the bar cannot go up",
               "How to test strength without ever performing a 1RM"],
        "de": ["Woher Kraftzuwachs kommt und was sich in welcher Woche verändert",
               "Wie viel Volumen genügt und wie nah am Versagen du wirklich trainieren musst",
               "Die sechs Wege progressiver Überlastung, wenn das Gewicht nicht steigen kann",
               "Wie du Kraft testest, ohne je ein 1RM zu machen"]},
 contents={"nl": ["Deel I — Hoe kracht ontstaat: tijdlijn, specificiteit en wat kracht niet oplost",
                  "Deel II — De variabelen: belasting, volume, falen, frequentie, tempo, autoregulatie",
                  "Deel III — Het programma: oefenselectie, week, jaar, massa, herstel",
                  "De drie twaalf-weken programma's en testen zonder 1RM",
                  "Bijlagen: oefenbibliotheek met techniekstandaarden, tabellen, logboek"],
           "en": ["Part I — How strength develops: timeline, specificity and what strength does not fix",
                  "Part II — The variables: load, volume, failure, frequency, tempo, autoregulation",
                  "Part III — The programme: exercise selection, week, year, mass, recovery",
                  "The three twelve-week programmes and testing without a 1RM",
                  "Appendices: exercise library with technique standards, tables, logbook"],
           "de": ["Teil I — Wie Kraft entsteht: Zeitachse, Spezifität und was Kraft nicht löst",
                  "Teil II — Die Variablen: Last, Volumen, Versagen, Frequenz, Tempo, Autoregulation",
                  "Teil III — Das Programm: Übungsauswahl, Woche, Jahr, Masse, Erholung",
                  "Die drei Zwölf-Wochen-Programme und Testen ohne 1RM",
                  "Anhänge: Übungsbibliothek mit Technikstandards, Tabellen, Logbuch"]},
 teaserQuote={"nl": "Sterk is een middel. De vraag is niet hoeveel je tilt, maar wat het je op het veld oplevert.",
              "en": "Strong is a means. The question is not how much you lift, but what it buys you on the field.",
              "de": "Stark ist ein Mittel. Die Frage ist nicht, wie viel du hebst, sondern was es dir auf dem Feld bringt."}),
# -------------------------------------------------------------- STRENGTH pro
dict(id="strength-foundations-pro", family="strength", version="pro", nr="02",
 pages=61, weeks=12, category="strength", phase=["off-season", "pre-season", "season", "power"],
 recommendFor=["strength:below", "asymmetry:yes"], featured=False,
 badges={"nl": ["Pro", "IJshockey", "61 pagina's"], "en": ["Pro", "Ice hockey", "61 pages"], "de": ["Pro", "Eishockey", "61 Seiten"]},
 title={"nl": "Strength Foundations — Pro", "en": "Strength Foundations — Pro", "de": "Strength Foundations — Pro"},
 tagline={"nl": "Sterker worden voor ijshockey, zonder je schaatsen te verliezen.",
          "en": "Getting stronger for ice hockey without losing your skating.",
          "de": "Stärker werden für Eishockey, ohne dein Skating zu verlieren."},
 summary={"nl": "Het krachtprofiel van een ijshockeyspeler: absoluut versus relatief, de massa-afweging, het onderlichaam per vlak en per been, contact, romp en nek. Met een off-season krachtblok van twaalf weken, een in-season model en een 25-minutenprotocol voor drukke weken.",
          "en": "The strength profile of an ice hockey player: absolute versus relative, the mass trade-off, the lower body per plane and per leg, contact, trunk and neck. With a twelve-week off-season strength block, an in-season model and a 25-minute protocol for busy weeks.",
          "de": "Das Kraftprofil eines Eishockeyspielers: absolut versus relativ, die Masse-Abwägung, der Unterkörper pro Ebene und pro Bein, Kontakt, Rumpf und Nacken. Mit einem zwölfwöchigen Off-Season-Kraftblock, einem In-Season-Modell und einem 25-Minuten-Protokoll für volle Wochen."},
 audience={"nl": "IJshockeyers die de Core kennen en willen weten hoeveel massa nog helpt en vanaf wanneer hij kost.",
           "en": "Ice hockey players who know the Core and want to know how much mass still helps and when it starts costing.",
           "de": "Eishockeyspieler, die die Core kennen und wissen wollen, wie viel Masse noch hilft und ab wann sie kostet."},
 learn={"nl": ["Waar de grens ligt tussen sterk genoeg en te zwaar voor je acceleratie",
               "Oefenselectie per vlak, per been, en waarom de squat geen model van de schaatsafzet is",
               "De posterior chain in een sport die je nooit laat sprinten",
               "Krachttraining inpassen naast een hoog ijsvolume zonder interferentie"],
        "en": ["Where the line sits between strong enough and too heavy for your acceleration",
               "Exercise selection per plane and per leg, and why the squat is not a model of the skating stride",
               "The posterior chain in a sport that never lets you sprint",
               "Fitting strength training alongside a high ice volume without interference"],
        "de": ["Wo die Grenze liegt zwischen stark genug und zu schwer für deine Beschleunigung",
               "Übungsauswahl pro Ebene und pro Bein — und warum die Kniebeuge kein Modell des Abstoßes ist",
               "Die hintere Kette in einer Sportart, die dich nie sprinten lässt",
               "Krafttraining neben hohem Eisvolumen einbauen, ohne Interferenz"]},
 contents={"nl": ["Deel I — Wat ijshockey van kracht vraagt: profiel, massa, vlakken, contact, nek",
                  "Deel II — De aanpassingen: oefenselectie, posterior chain, heup en lies, grip",
                  "Deel III — Het seizoen: off-season blok, massaprotocol, in-season, monitoring",
                  "Deel IV — Positieaccenten, jeugd en het meerjarenpad",
                  "Bonusmodules: testbatterij, 25-minutenprotocol, nek- en schouderprogramma, keeperbijlage"],
           "en": ["Part I — What ice hockey demands of strength: profile, mass, planes, contact, neck",
                  "Part II — The adjustments: exercise selection, posterior chain, hip and groin, grip",
                  "Part III — The season: off-season block, mass protocol, in-season, monitoring",
                  "Part IV — Positional accents, youth and the multi-year pathway",
                  "Bonus modules: test battery, 25-minute protocol, neck and shoulder programme, goalie appendix"],
           "de": ["Teil I — Was Eishockey von Kraft verlangt: Profil, Masse, Ebenen, Kontakt, Nacken",
                  "Teil II — Die Anpassungen: Übungsauswahl, hintere Kette, Hüfte und Leiste, Griff",
                  "Teil III — Die Saison: Off-Season-Block, Masseprotokoll, In-Season, Monitoring",
                  "Teil IV — Positionsakzente, Jugend und der Mehrjahresweg",
                  "Bonusmodule: Testbatterie, 25-Minuten-Protokoll, Nacken- und Schulterprogramm, Torwart-Anhang"]},
 teaserQuote={"nl": "Sterk genoeg, licht genoeg. Elke kilo die niet meegroeit met je krachtproductie kost je acceleratie.",
              "en": "Strong enough, light enough. Every kilo that does not grow with your force production costs you acceleration.",
              "de": "Stark genug, leicht genug. Jedes Kilo, das nicht mit deiner Kraftproduktion mitwächst, kostet dich Beschleunigung."}),
# ---------------------------------------------------------------- SPEED core
dict(id="speed-foundations-core", family="speed", version="core", nr="03",
 pages=60, weeks=12, category="speed", phase=["off-season", "pre-season", "agility"],
 recommendFor=["accel:below", "topspeed:below"], featured=True,
 badges={"nl": ["12 weken", "Core", "60 pagina's"], "en": ["12 weeks", "Core", "60 pages"], "de": ["12 Wochen", "Core", "60 Seiten"]},
 title={"nl": "Speed Foundations — Core", "en": "Speed Foundations — Core", "de": "Speed Foundations — Core"},
 tagline={"nl": "Acceleratie, topsnelheid en sprintmechanica — sneller worden, niet alleen fitter.",
          "en": "Acceleration, top speed and sprint mechanics — getting faster, not just fitter.",
          "de": "Beschleunigung, Höchstgeschwindigkeit und Sprintmechanik — schneller werden, nicht nur fitter."},
 summary={"nl": "Snelheid is de meest gewaardeerde en slechtst getrainde eigenschap in teamsport. Dit handboek behandelt krachtoriëntatie, het acceleratiemodel, het topsnelheidsmodel en de snelheidsreserve, met sprints, sleds, hordes en heuvels als middelen — plus drie twaalf-weken programma's en een hoofdstuk over hamstrings.",
          "en": "Speed is the most valued and worst trained quality in team sport. This handbook covers force orientation, the acceleration model, the top-speed model and speed reserve, with sprints, sleds, hurdles and hills as tools — plus three twelve-week programmes and a chapter on hamstrings.",
          "de": "Schnelligkeit ist die am höchsten geschätzte und am schlechtesten trainierte Eigenschaft im Teamsport. Dieses Handbuch behandelt Kraftorientierung, das Beschleunigungsmodell, das Höchstgeschwindigkeitsmodell und die Geschwindigkeitsreserve — mit Sprints, Schlitten, Hürden und Hügeln als Mitteln, dazu drei Zwölf-Wochen-Programme und ein Kapitel über die Ischiocrurale."},
 audience={"nl": "Sporters die sneller willen worden en nu sprinten gebruiken als conditiemiddel in plaats van als trainingsdoel.",
           "en": "Athletes who want to get faster and currently use sprinting as conditioning rather than as a training goal.",
           "de": "Sportler, die schneller werden wollen und Sprints bisher als Konditionsmittel statt als Trainingsziel nutzen."},
 learn={"nl": ["Waarom de richting van je duw meer bepaalt dan hoe hard je duwt",
               "Het verschil tussen acceleratie en topsnelheid, en waarom je ze apart traint",
               "Waarom topsnelheid ook telt als je hem in je sport nooit haalt",
               "Hoe je hamstrings beschermt door ze juist bloot te stellen aan hoge snelheden"],
        "en": ["Why the direction of your push matters more than how hard you push",
               "The difference between acceleration and top speed, and why you train them separately",
               "Why top speed matters even if your sport never lets you reach it",
               "How to protect hamstrings by exposing them to high speeds rather than avoiding them"],
        "de": ["Warum die Richtung deines Abdrucks mehr zählt als seine Härte",
               "Der Unterschied zwischen Beschleunigung und Höchstgeschwindigkeit — und warum man sie getrennt trainiert",
               "Warum Höchstgeschwindigkeit zählt, auch wenn du sie im Spiel nie erreichst",
               "Wie du die Ischiocrurale schützt, indem du sie hohen Geschwindigkeiten aussetzt"]},
 contents={"nl": ["Deel I — Hoe snelheid werkt: krachtoriëntatie, acceleratie, topsnelheid, snelheidsreserve",
                  "Deel II — De techniek: acceleratiemodel, topsnelheidsmodel, armen en romp, drills",
                  "Deel III — De training: middelen, volume, warming-up, week, jaar, hamstrings",
                  "Meten, interpreteren en de drie twaalf-weken programma's",
                  "Bijlagen: drillbibliotheek, oriëntatiewaarden, videochecklist, de twintig fouten"],
           "en": ["Part I — How speed works: force orientation, acceleration, top speed, speed reserve",
                  "Part II — The technique: acceleration model, top-speed model, arms and trunk, drills",
                  "Part III — The training: tools, volume, warm-up, week, year, hamstrings",
                  "Measuring, interpreting and the three twelve-week programmes",
                  "Appendices: drill library, orientation values, video checklist, the twenty mistakes"],
           "de": ["Teil I — Wie Schnelligkeit funktioniert: Kraftorientierung, Beschleunigung, Höchstgeschwindigkeit, Reserve",
                  "Teil II — Die Technik: Beschleunigungsmodell, Höchstgeschwindigkeitsmodell, Arme und Rumpf, Drills",
                  "Teil III — Das Training: Mittel, Volumen, Warm-up, Woche, Jahr, Ischiocrurale",
                  "Messen, interpretieren und die drei Zwölf-Wochen-Programme",
                  "Anhänge: Drill-Bibliothek, Orientierungswerte, Video-Checkliste, die zwanzig Fehler"]},
 teaserQuote={"nl": "Snelheid is een vaardigheid. Bijna iedereen wil sneller worden; bijna niemand traint ervoor.",
              "en": "Speed is a skill. Almost everyone wants to be faster; almost nobody trains for it.",
              "de": "Schnelligkeit ist eine Fähigkeit. Fast jeder will schneller werden; fast niemand trainiert dafür."}),
# ----------------------------------------------------------------- SPEED pro
dict(id="speed-foundations-pro", family="speed", version="pro", nr="03",
 pages=54, weeks=12, category="speed", phase=["off-season", "pre-season", "season", "agility"],
 recommendFor=["accel:below", "topspeed:below"], featured=True,
 badges={"nl": ["Pro", "IJshockey", "54 pagina's"], "en": ["Pro", "Ice hockey", "54 pages"], "de": ["Pro", "Eishockey", "54 Seiten"]},
 title={"nl": "Speed Foundations — Pro", "en": "Speed Foundations — Pro", "de": "Speed Foundations — Pro"},
 tagline={"nl": "Schaatssnelheid: de eerste drie passen, crossovers en transitions.",
          "en": "Skating speed: the first three strides, crossovers and transitions.",
          "de": "Skating-Speed: die ersten drei Schritte, Crossovers und Transitions."},
 summary={"nl": "Wat schaatssnelheid werkelijk bepaalt, op het ijs én ernaast. De start, topsnelheid op het ijs, crossovers als grootste snelheidsbron, transitions en achterwaarts. Plus off-ice sprinten, hamstrings in een sport zonder sprintvolume, en een in-season blok om snelheid vast te houden.",
          "en": "What skating speed actually depends on, on and off the ice. The start, top speed on ice, crossovers as the biggest source of speed, transitions and backwards skating. Plus off-ice sprinting, hamstrings in a sport without sprint volume, and an in-season block to hold onto speed.",
          "de": "Was Skating-Speed wirklich bestimmt — auf dem Eis und daneben. Der Start, Höchstgeschwindigkeit auf dem Eis, Crossovers als größte Geschwindigkeitsquelle, Transitions und Rückwärtslaufen. Dazu Off-Ice-Sprints, Ischiocrurale in einer Sportart ohne Sprintvolumen und ein In-Season-Block."},
 audience={"nl": "IJshockeyers die de Core kennen en willen weten waar hun snelheid op het ijs werkelijk vandaan komt.",
           "en": "Ice hockey players who know the Core and want to know where their speed on ice actually comes from.",
           "de": "Eishockeyspieler, die die Core kennen und wissen wollen, woher ihre Geschwindigkeit auf dem Eis wirklich kommt."},
 learn={"nl": ["Waarom crossovers vaak meer snelheid opleveren dan rechtuit schaatsen",
               "Wat je in de eerste drie tot vijf passen anders doet dan bij topsnelheid",
               "Wat off-ice sprinten wel en niet doet voor je schaatssnelheid",
               "Hoe je snelheid vasthoudt in weken met twee en drie wedstrijden"],
        "en": ["Why crossovers often produce more speed than skating straight",
               "What you do differently in the first three to five strides than at top speed",
               "What off-ice sprinting does and does not do for your skating speed",
               "How to hold onto speed in weeks with two and three games"],
        "de": ["Warum Crossovers oft mehr Geschwindigkeit bringen als geradeaus laufen",
               "Was du in den ersten drei bis fünf Schritten anders machst als bei Höchstgeschwindigkeit",
               "Was Off-Ice-Sprints für deine Skating-Geschwindigkeit leisten — und was nicht",
               "Wie du Geschwindigkeit in Wochen mit zwei und drei Spielen hältst"]},
 contents={"nl": ["Deel I — Snelheid op het ijs: start, topsnelheid, crossovers, transitions",
                  "Deel II — De training op het ijs: snelheidsblok, weerstand, techniek, materiaal",
                  "Deel III — Off-ice en het seizoen: sprinten, hamstrings, off-season, in-season",
                  "Deel IV — Positieaccenten, jeugd en terugkeer naar snelheid na blessure",
                  "Bonusmodules: testbatterijen, 15-minuten on-ice blok, crossoverprogramma, keeperbijlage"],
           "en": ["Part I — Speed on ice: start, top speed, crossovers, transitions",
                  "Part II — Training on ice: speed block, resistance, technique, equipment",
                  "Part III — Off-ice and the season: sprinting, hamstrings, off-season, in-season",
                  "Part IV — Positional accents, youth and returning to speed after injury",
                  "Bonus modules: test batteries, 15-minute on-ice block, crossover programme, goalie appendix"],
           "de": ["Teil I — Geschwindigkeit auf dem Eis: Start, Höchstgeschwindigkeit, Crossovers, Transitions",
                  "Teil II — Training auf dem Eis: Speed-Block, Widerstand, Technik, Material",
                  "Teil III — Off-Ice und die Saison: Sprints, Ischiocrurale, Off-Season, In-Season",
                  "Teil IV — Positionsakzente, Jugend und Rückkehr zur Geschwindigkeit nach Verletzung",
                  "Bonusmodule: Testbatterien, 15-Minuten-Block auf dem Eis, Crossover-Programm, Torwart-Anhang"]},
 teaserQuote={"nl": "De eerste drie passen beslissen meer duels dan je topsnelheid ooit zal doen.",
              "en": "The first three strides decide more duels than your top speed ever will.",
              "de": "Die ersten drei Schritte entscheiden mehr Zweikämpfe als deine Höchstgeschwindigkeit je wird."}),
# -------------------------------------------------------------- AGILITY core
dict(id="agility-foundations-core", family="agility", version="core", nr="04",
 pages=59, weeks=12, category="speed", phase=["pre-season", "season", "agility"],
 recommendFor=["cod:below"], featured=False,
 badges={"nl": ["12 weken", "Core", "59 pagina's"], "en": ["12 weeks", "Core", "59 pages"], "de": ["12 Wochen", "Core", "59 Seiten"]},
 title={"nl": "Agility Foundations — Core", "en": "Agility Foundations — Core", "de": "Agility Foundations — Core"},
 tagline={"nl": "Afremmen, van richting veranderen en reageren — de kwaliteit die wedstrijden beslist.",
          "en": "Braking, changing direction and reacting — the quality that decides games.",
          "de": "Abbremsen, Richtungswechsel und Reagieren — die Qualität, die Spiele entscheidet."},
 summary={"nl": "In vrijwel geen enkele sport win je een duel door rechtuit te sprinten. Dit handboek behandelt het verschil tussen change of direction en agility, het remmodel van de laatste twee passen, het draaimodel, de knie, en een reactieve progressie — plus drie twaalf-weken programma's en de 505-test.",
          "en": "In almost no sport do you win a duel by sprinting in a straight line. This handbook covers the difference between change of direction and agility, the braking model of the last two steps, the turning model, the knee, and a reactive progression — plus three twelve-week programmes and the 505 test.",
          "de": "In kaum einer Sportart gewinnt man einen Zweikampf durch geradeaus sprinten. Dieses Handbuch behandelt den Unterschied zwischen Change of Direction und Agilität, das Bremsmodell der letzten zwei Schritte, das Drehmodell, das Knie und eine reaktive Progression — dazu drei Zwölf-Wochen-Programme und den 505-Test."},
 audience={"nl": "Sporters en coaches die agility nu trainen met pionnetjes en willen weten waarom dat weinig oplevert.",
           "en": "Athletes and coaches who currently train agility with cones and want to know why that yields little.",
           "de": "Sportler und Trainer, die Agilität mit Hütchen trainieren und wissen wollen, warum das wenig bringt."},
 learn={"nl": ["Waarom change of direction en agility niet hetzelfde zijn, en wat je dan wél traint",
               "Hoe afremmen in de laatste twee passen bepaalt hoe snel je weer weg bent",
               "Waarom de hoek van de richtingsverandering de opgave verandert",
               "Hoe je van gesloten drills naar echt reageren komt, in vier stappen"],
        "en": ["Why change of direction and agility are not the same, and what to train instead",
               "How braking in the last two steps decides how fast you leave again",
               "Why the angle of the direction change changes the task",
               "How to move from closed drills to genuine reacting, in four steps"],
        "de": ["Warum Change of Direction und Agilität nicht dasselbe sind — und was du stattdessen trainierst",
               "Wie das Abbremsen in den letzten zwei Schritten bestimmt, wie schnell du wieder weg bist",
               "Warum der Winkel des Richtungswechsels die Aufgabe verändert",
               "Wie du in vier Schritten von geschlossenen Drills zu echtem Reagieren kommst"]},
 contents={"nl": ["Deel I — Wat agility werkelijk is: CoD versus agility, afremmen, hoek, waarnemen",
                  "Deel II — De techniek: het remmodel, het draaimodel, de knie, voet en romp",
                  "Deel III — De training: middelen, volume, reactieve progressie, kracht voor afremmen",
                  "Testen (505, deficit, reactietijd) en de drie twaalf-weken programma's",
                  "Bijlagen: drillbibliotheek, oriëntatiewaarden, videochecklist, de twintig fouten"],
           "en": ["Part I — What agility really is: CoD versus agility, braking, angle, perception",
                  "Part II — The technique: braking model, turning model, the knee, foot and trunk",
                  "Part III — The training: tools, volume, reactive progression, strength for braking",
                  "Testing (505, deficit, reaction time) and the three twelve-week programmes",
                  "Appendices: drill library, orientation values, video checklist, the twenty mistakes"],
           "de": ["Teil I — Was Agilität wirklich ist: CoD versus Agilität, Abbremsen, Winkel, Wahrnehmung",
                  "Teil II — Die Technik: Bremsmodell, Drehmodell, das Knie, Fuß und Rumpf",
                  "Teil III — Das Training: Mittel, Volumen, reaktive Progression, Kraft zum Abbremsen",
                  "Testen (505, Deficit, Reaktionszeit) und die drei Zwölf-Wochen-Programme",
                  "Anhänge: Drill-Bibliothek, Orientierungswerte, Video-Checkliste, die zwanzig Fehler"]},
 teaserQuote={"nl": "Remmen is de vaardigheid. Je wint het duel door eerder te stoppen, niet door harder te sprinten.",
              "en": "Braking is the skill. You win the duel by stopping earlier, not by sprinting harder.",
              "de": "Bremsen ist die Fähigkeit. Du gewinnst den Zweikampf, indem du früher stoppst, nicht härter sprintest."}),
# --------------------------------------------------------------- AGILITY pro
dict(id="agility-foundations-pro", family="agility", version="pro", nr="04",
 pages=56, weeks=8, category="speed", phase=["pre-season", "season", "agility"],
 recommendFor=["cod:below"], featured=False,
 badges={"nl": ["Pro", "IJshockey", "56 pagina's"], "en": ["Pro", "Ice hockey", "56 pages"], "de": ["Pro", "Eishockey", "56 Seiten"]},
 title={"nl": "Agility Foundations — Pro", "en": "Agility Foundations — Pro", "de": "Agility Foundations — Pro"},
 tagline={"nl": "Stops, tight turns, pivots en het lezen van het spel — waar de grond niet meewerkt.",
          "en": "Stops, tight turns, pivots and reading the game — where the ground does not help.",
          "de": "Stops, Tight Turns, Pivots und Spiellesen — dort, wo der Untergrund nicht mithilft."},
 summary={"nl": "Richting veranderen op ijs is een ander probleem dan op gras. Dit handboek behandelt edges, de hockey stop, tight turns, de mohawk, pivots en transitions, plus wat je ziet voordat je beweegt. Met off-ice remwerk als compensatie voor de prikkel die het ijs niet geeft, en een heup- en liesprogramma.",
          "en": "Changing direction on ice is a different problem than on grass. This handbook covers edges, the hockey stop, tight turns, the mohawk, pivots and transitions, plus what you see before you move. With off-ice braking work to compensate for the stimulus the ice does not provide, and a hip and groin programme.",
          "de": "Richtungswechsel auf Eis ist ein anderes Problem als auf Rasen. Dieses Handbuch behandelt Edges, den Hockey Stop, Tight Turns, den Mohawk, Pivots und Transitions — dazu, was du siehst, bevor du dich bewegst. Mit Off-Ice-Bremsarbeit als Ausgleich und einem Hüft- und Leistenprogramm."},
 audience={"nl": "IJshockeyers en staf die weten dat edges het verschil maken en willen weten hoe je ze traint.",
           "en": "Ice hockey players and staff who know edges make the difference and want to know how to train them.",
           "de": "Eishockeyspieler und Staff, die wissen, dass Edges den Unterschied machen — und wie man sie trainiert."},
 learn={"nl": ["Wanneer stoppen sneller is dan draaien, en wanneer het je tijd kost",
               "Hoe je pivots en transitions traint zonder je heup en lies te overbelasten",
               "Waarom off-ice remwerk geen aanvulling is maar een compensatie",
               "Hoe je reactief werk op het ijs opbouwt in plaats van drills af te draaien"],
        "en": ["When stopping is faster than turning, and when it costs you time",
               "How to train pivots and transitions without overloading hip and groin",
               "Why off-ice braking work is not an addition but a compensation",
               "How to build reactive work on ice instead of running through drills"],
        "de": ["Wann Stoppen schneller ist als Drehen — und wann es Zeit kostet",
               "Wie du Pivots und Transitions trainierst, ohne Hüfte und Leiste zu überlasten",
               "Warum Off-Ice-Bremsarbeit keine Ergänzung ist, sondern ein Ausgleich",
               "Wie du reaktive Arbeit auf dem Eis aufbaust, statt Drills abzuspulen"]},
 contents={"nl": ["Deel I — Richting veranderen op ijs: edges, stops, tight turns, pivots",
                  "Deel II — Reageren in de wedstrijd: waarnemen, hoofd omhoog, kleine ruimtes",
                  "Deel III — Off-ice en het seizoen: remwerk, heup en lies, off-season, in-season",
                  "Deel IV — Positieaccenten, jeugd en terugkeer na blessure",
                  "Bonusmodules: testbatterijen, 15-minuten edge-blok, deceleratieprogramma van acht weken"],
           "en": ["Part I — Changing direction on ice: edges, stops, tight turns, pivots",
                  "Part II — Reacting in the game: perception, head up, small spaces",
                  "Part III — Off-ice and the season: braking work, hip and groin, off-season, in-season",
                  "Part IV — Positional accents, youth and return after injury",
                  "Bonus modules: test batteries, 15-minute edge block, eight-week deceleration programme"],
           "de": ["Teil I — Richtungswechsel auf dem Eis: Edges, Stops, Tight Turns, Pivots",
                  "Teil II — Reagieren im Spiel: Wahrnehmung, Kopf hoch, enge Räume",
                  "Teil III — Off-Ice und die Saison: Bremsarbeit, Hüfte und Leiste, Off-Season, In-Season",
                  "Teil IV — Positionsakzente, Jugend und Rückkehr nach Verletzung",
                  "Bonusmodule: Testbatterien, 15-Minuten-Edge-Block, achtwöchiges Deceleration-Programm"]},
 teaserQuote={"nl": "Edges beslissen. Niet de spieren die je in de gym ziet, maar de hoek waaronder je staal het ijs raakt.",
              "en": "Edges decide. Not the muscles you see in the gym, but the angle at which your steel meets the ice.",
              "de": "Edges entscheiden. Nicht die Muskeln aus dem Gym, sondern der Winkel, in dem dein Stahl das Eis trifft."}),
# --------------------------------------------------------------- SEASON core
dict(id="season-foundations-core", family="season", version="core", nr="05",
 pages=57, weeks=None, category="conditioning", phase=["season"],
 recommendFor=["engine:below"], featured=False,
 badges={"nl": ["Seizoenslang", "Core", "57 pagina's"], "en": ["Season-long", "Core", "57 pages"], "de": ["Ganze Saison", "Core", "57 Seiten"]},
 title={"nl": "Season Foundations — Core", "en": "Season Foundations — Core", "de": "Season Foundations — Core"},
 tagline={"nl": "In-season performance: presteren over een heel seizoen zonder in te zakken.",
          "en": "In-season performance: performing across a full season without dropping off.",
          "de": "In-Season-Performance: über eine ganze Saison leisten, ohne einzubrechen."},
 summary={"nl": "De meeste sporters worden in de zomer beter en in het seizoen langzaam slechter. Dat is geen pech maar het voorspelbare gevolg van vier doelen die om dezelfde week vechten. Dit handboek geeft een monitoringsysteem in vier getallen, weekmodellen, beslisregels en een resetweek.",
          "en": "Most athletes improve in summer and slowly decline during the season. That is not bad luck but the predictable result of four goals fighting over the same week. This handbook gives a four-number monitoring system, week models, decision rules and a reset week.",
          "de": "Die meisten Sportler werden im Sommer besser und in der Saison langsam schlechter. Das ist kein Pech, sondern die vorhersehbare Folge von vier Zielen, die um dieselbe Woche kämpfen. Dieses Handbuch liefert ein Monitoringsystem in vier Zahlen, Wochenmodelle, Entscheidungsregeln und eine Reset-Woche."},
 audience={"nl": "Sporters en staf die in februari langzamer zijn dan in september en willen weten waar dat vandaan komt.",
           "en": "Athletes and staff who are slower in February than in September and want to know why.",
           "de": "Sportler und Staff, die im Februar langsamer sind als im September und wissen wollen, warum."},
 learn={"nl": ["Welke vier getallen genoeg zijn om je belasting te sturen zonder dure apparatuur",
               "Wanneer één afwijkende meting ruis is en wanneer twee een beslissing zijn",
               "Wat je per kwaliteit vasthoudt als er maar één sessie in de week past",
               "Hoe een resetweek eruitziet, en wanneer je hem inplant"],
        "en": ["Which four numbers are enough to steer your load without expensive equipment",
               "When one deviating measurement is noise and two are a decision",
               "What to hold onto per quality when only one session fits in the week",
               "What a reset week looks like, and when to schedule it"],
        "de": ["Welche vier Zahlen genügen, um deine Belastung ohne teure Geräte zu steuern",
               "Wann eine abweichende Messung Rauschen ist und wann zwei eine Entscheidung sind",
               "Was du pro Qualität hältst, wenn nur eine Einheit in die Woche passt",
               "Wie eine Reset-Woche aussieht und wann du sie einplanst"]},
 contents={"nl": ["Deel I — Wat een seizoen met je doet: verval, belasting, vermoeidheid herkennen",
                  "Deel II — Meten en bijsturen: sRPE, sprongmeting, wellness, beslisregels",
                  "Deel III — De week en het seizoen: weekmodellen, herstel, slaap, reizen, voeding",
                  "De resetweek, taperen en de seizoensevaluatie",
                  "Bijlagen: alle tabellen en beslisregels, formulieren, logboek, de twintig fouten"],
           "en": ["Part I — What a season does to you: decline, load, recognising fatigue",
                  "Part II — Measuring and steering: sRPE, jump testing, wellness, decision rules",
                  "Part III — The week and the season: week models, recovery, sleep, travel, nutrition",
                  "The reset week, tapering and the season review",
                  "Appendices: all tables and decision rules, forms, logbook, the twenty mistakes"],
           "de": ["Teil I — Was eine Saison mit dir macht: Abfall, Belastung, Ermüdung erkennen",
                  "Teil II — Messen und steuern: sRPE, Sprungmessung, Wellness, Entscheidungsregeln",
                  "Teil III — Woche und Saison: Wochenmodelle, Erholung, Schlaf, Reisen, Ernährung",
                  "Die Reset-Woche, Tapering und die Saisonauswertung",
                  "Anhänge: alle Tabellen und Entscheidungsregeln, Formulare, Logbuch, die zwanzig Fehler"]},
 teaserQuote={"nl": "Je hebt je voorbereiding niet verloren. Je hebt hem alleen niet onderhouden.",
              "en": "You did not lose your pre-season. You just never maintained it.",
              "de": "Du hast deine Vorbereitung nicht verloren. Du hast sie nur nicht erhalten."}),
# ---------------------------------------------------------------- SEASON pro
dict(id="season-foundations-pro", family="season", version="pro", nr="05",
 pages=63, weeks=None, category="conditioning", phase=["season"],
 recommendFor=["engine:below"], featured=True,
 badges={"nl": ["Seizoenslang", "Pro", "IJshockey"], "en": ["Season-long", "Pro", "Ice hockey"], "de": ["Ganze Saison", "Pro", "Eishockey"]},
 title={"nl": "Season Foundations — Pro", "en": "Season Foundations — Pro", "de": "Season Foundations — Pro"},
 tagline={"nl": "Zeven maanden, vijftig wedstrijden, tweeduizend kilometer bus.",
          "en": "Seven months, fifty games, two thousand kilometres of bus.",
          "de": "Sieben Monate, fünfzig Spiele, zweitausend Kilometer Bus."},
 summary={"nl": "Het ijshockeyseizoen als belastingsprobleem: het weekendritme, ijsvolume dat niet in het schema staat, reizen als structurele belasting en positieverschillen. Met het vrijdag-zondag model, een monitoringformulier voor teams, een busprotocol en een plan voor de tweede seizoenshelft.",
          "en": "The ice hockey season as a load problem: the weekend rhythm, ice volume that never shows up in the schedule, travel as structural load and positional differences. With the Friday–Sunday model, a team monitoring form, a bus protocol and a plan for the second half of the season.",
          "de": "Die Eishockeysaison als Belastungsproblem: der Wochenendrhythmus, Eisvolumen, das nie im Plan steht, Reisen als strukturelle Belastung und Positionsunterschiede. Mit dem Freitag-Sonntag-Modell, einem Monitoringbogen für Teams, einem Busprotokoll und einem Plan für die zweite Saisonhälfte."},
 audience={"nl": "IJshockeyspelers en staf die de Core kennen en het willen toepassen op een echte competitiekalender.",
           "en": "Ice hockey players and staff who know the Core and want to apply it to a real competition calendar.",
           "de": "Eishockeyspieler und Staff, die die Core kennen und sie auf einen echten Spielplan anwenden wollen."},
 learn={"nl": ["Hoe een week met wedstrijden op vrijdag en zondag eruit hoort te zien",
               "Waarom ijsvolume de belasting is die nooit in het schema staat",
               "Wat je met de coach afspreekt, en hoe je dat gesprek voert",
               "Hoe je de tweede seizoenshelft ingaat zonder de eerste te hebben opgebruikt"],
        "en": ["What a week with Friday and Sunday games should look like",
               "Why ice volume is the load that never shows up in the schedule",
               "What to agree with the coach, and how to have that conversation",
               "How to enter the second half of the season without having spent the first"],
        "de": ["Wie eine Woche mit Spielen am Freitag und Sonntag aussehen sollte",
               "Warum Eisvolumen die Belastung ist, die nie im Plan steht",
               "Was du mit dem Trainer vereinbarst — und wie du dieses Gespräch führst",
               "Wie du in die zweite Saisonhälfte gehst, ohne die erste verbraucht zu haben"]},
 contents={"nl": ["Deel I — Het ijshockeyseizoen: weekendritme, ijsvolume, reizen, posities",
                  "Deel II — De week inrichten: vrijdag-zondag model, gameday, morning skate, monitoring",
                  "Deel III — Herstel en volhouden: de nacht na de wedstrijd, eten onderweg, lies en heup",
                  "Deel IV — Het scherpe eind: tweede seizoenshelft, play-offs, jeugd",
                  "Bonusmodules: weekmodellen per ritme, teamformulier, busprotocol, gameday-protocol"],
           "en": ["Part I — The ice hockey season: weekend rhythm, ice volume, travel, positions",
                  "Part II — Structuring the week: Friday–Sunday model, gameday, morning skate, monitoring",
                  "Part III — Recovery and lasting: the night after the game, eating on the road, groin and hip",
                  "Part IV — The sharp end: second half, play-offs, youth",
                  "Bonus modules: week models per rhythm, team form, bus protocol, gameday protocol"],
           "de": ["Teil I — Die Eishockeysaison: Wochenendrhythmus, Eisvolumen, Reisen, Positionen",
                  "Teil II — Die Woche gestalten: Freitag-Sonntag-Modell, Gameday, Morning Skate, Monitoring",
                  "Teil III — Erholung und Durchhalten: die Nacht danach, Essen unterwegs, Leiste und Hüfte",
                  "Teil IV — Das scharfe Ende: zweite Saisonhälfte, Play-offs, Jugend",
                  "Bonusmodule: Wochenmodelle pro Rhythmus, Teambogen, Busprotokoll, Gameday-Protokoll"]},
 teaserQuote={"nl": "Vrijdag en zondag. Daartussen ligt geen trainingsweek, maar een herstelvraagstuk.",
              "en": "Friday and Sunday. What lies between them is not a training week but a recovery problem.",
              "de": "Freitag und Sonntag. Dazwischen liegt keine Trainingswoche, sondern eine Erholungsfrage."}),
# ------------------------------------------------------------ PRE-SEASON core
dict(id="preseason-foundations-core", family="preseason", version="core", nr="06",
 pages=58, weeks=12, category="conditioning", phase=["off-season", "pre-season"],
 recommendFor=["engine:below"], featured=False,
 badges={"nl": ["12 / 8 / 6 weken", "Core", "58 pagina's"], "en": ["12 / 8 / 6 weeks", "Core", "58 pages"], "de": ["12 / 8 / 6 Wochen", "Core", "58 Seiten"]},
 title={"nl": "Pre-Season Foundations — Core", "en": "Pre-Season Foundations — Core", "de": "Pre-Season Foundations — Core"},
 tagline={"nl": "De voorbereiding: de enige periode waarin je echt kunt bouwen.",
          "en": "Pre-season: the only period in which you can genuinely build.",
          "de": "Die Vorbereitung: die einzige Phase, in der du wirklich aufbauen kannst."},
 summary={"nl": "Alles wat je in het seizoen probeert te redden, wordt in de zomer gebouwd. Dit handboek behandelt de fasen van een voorbereiding, de audit, prioriteren, achteruit plannen vanaf dag één, blokvolgorde en concurrent training — met drie complete plannen van twaalf, acht en zes weken.",
          "en": "Everything you try to salvage during the season is built in the summer. This handbook covers the phases of a pre-season, the audit, prioritising, planning backwards from day one, block order and concurrent training — with three complete plans of twelve, eight and six weeks.",
          "de": "Alles, was du in der Saison zu retten versuchst, wird im Sommer gebaut. Dieses Handbuch behandelt die Phasen einer Vorbereitung, das Audit, Priorisieren, Rückwärtsplanen ab Tag eins, Blockreihenfolge und Concurrent Training — mit drei kompletten Plänen über zwölf, acht und sechs Wochen."},
 audience={"nl": "Sporters en staf die een voorbereiding willen plannen in plaats van hem te laten gebeuren.",
           "en": "Athletes and staff who want to plan a pre-season rather than let it happen.",
           "de": "Sportler und Staff, die eine Vorbereitung planen statt sie geschehen lassen wollen."},
 learn={"nl": ["Hoe je achteruit plant vanaf dag één van de competitie",
               "Waarom je niet alles tegelijk kunt ontwikkelen, en hoe je dus kiest",
               "Hoe je conditie, kracht en snelheid combineert zonder interferentie",
               "Wat de laatste twee weken voor de start wel en niet moeten bevatten"],
        "en": ["How to plan backwards from day one of the competition",
               "Why you cannot develop everything at once, and how to choose",
               "How to combine conditioning, strength and speed without interference",
               "What the last two weeks before the start should and should not contain"],
        "de": ["Wie du rückwärts ab Tag eins des Wettkampfs planst",
               "Warum du nicht alles gleichzeitig entwickeln kannst — und wie du wählst",
               "Wie du Kondition, Kraft und Schnelligkeit ohne Interferenz kombinierst",
               "Was die letzten zwei Wochen vor dem Start enthalten sollten und was nicht"]},
 contents={"nl": ["Deel I — Het plan maken: fasen, overgangsperiode, de audit, prioriteren",
                  "Deel II — De opbouw: blokvolgorde, concurrent training, conditie, opbouwramp",
                  "Deel III — Naar de start: specifiek blok, trainingskamp, oefenwedstrijden, laatste twee weken",
                  "De plannen: model A (12 weken), B (8 weken) en C (6 weken)",
                  "Bijlagen: tabellen en beslisregels, auditformulier, logboek, de twintig fouten"],
           "en": ["Part I — Making the plan: phases, transition period, the audit, prioritising",
                  "Part II — The build: block order, concurrent training, conditioning, ramp-up",
                  "Part III — Towards the start: specific block, camp, friendlies, the last two weeks",
                  "The plans: model A (12 weeks), B (8 weeks) and C (6 weeks)",
                  "Appendices: tables and decision rules, audit form, logbook, the twenty mistakes"],
           "de": ["Teil I — Den Plan machen: Phasen, Übergangsperiode, das Audit, Priorisieren",
                  "Teil II — Der Aufbau: Blockreihenfolge, Concurrent Training, Kondition, Aufbaurampe",
                  "Teil III — Zum Start: spezifischer Block, Trainingslager, Testspiele, die letzten zwei Wochen",
                  "Die Pläne: Modell A (12 Wochen), B (8 Wochen) und C (6 Wochen)",
                  "Anhänge: Tabellen und Entscheidungsregeln, Auditbogen, Logbuch, die zwanzig Fehler"]},
 teaserQuote={"nl": "Het seizoen wordt in de zomer gebouwd. In november kun je alleen nog beheren wat er staat.",
              "en": "The season is built in summer. By November you can only manage what is already there.",
              "de": "Die Saison wird im Sommer gebaut. Im November kannst du nur noch verwalten, was da ist."}),
# ------------------------------------------------------------- PRE-SEASON pro
dict(id="preseason-foundations-pro", family="preseason", version="pro", nr="06",
 pages=64, weeks=18, category="conditioning", phase=["off-season", "pre-season"],
 recommendFor=["engine:below"], featured=False,
 badges={"nl": ["18 weken", "Pro", "IJshockey"], "en": ["18 weeks", "Pro", "Ice hockey"], "de": ["18 Wochen", "Pro", "Eishockey"]},
 title={"nl": "Pre-Season Foundations — Pro", "en": "Pre-Season Foundations — Pro", "de": "Pre-Season Foundations — Pro"},
 tagline={"nl": "Achttien weken tussen de laatste wedstrijd en de eerste.",
          "en": "Eighteen weeks between the last game and the first.",
          "de": "Achtzehn Wochen zwischen dem letzten Spiel und dem ersten."},
 summary={"nl": "April tot september: de enige periode waarin een ijshockeyer echt kan bouwen. De audit van wat het seizoen heeft achtergelaten, het heup- en liesproject van de zomer, kracht in de vlakken die schaatsen vraagt, en wanneer je het ijs weer op gaat — met een week-voor-week model van achttien weken en een korter model van tien.",
          "en": "April to September: the only period in which an ice hockey player can truly build. The audit of what the season left behind, the summer hip and groin project, strength in the planes skating demands, and when to get back on the ice — with a week-by-week eighteen-week model and a shorter ten-week model.",
          "de": "April bis September: die einzige Phase, in der ein Eishockeyspieler wirklich aufbauen kann. Das Audit dessen, was die Saison hinterlassen hat, das Hüft- und Leistenprojekt des Sommers, Kraft in den Ebenen, die das Skating verlangt, und wann du zurück aufs Eis gehst — mit einem Achtzehn-Wochen-Modell Woche für Woche und einem kürzeren Zehn-Wochen-Modell."},
 audience={"nl": "IJshockeyers en staf die de zomer willen gebruiken in plaats van hem te laten verdampen.",
           "en": "Ice hockey players and staff who want to use the summer instead of letting it evaporate.",
           "de": "Eishockeyspieler und Staff, die den Sommer nutzen wollen, statt ihn verdampfen zu lassen."},
 learn={"nl": ["Hoe achttien weken eruitzien, week voor week, van laatste wedstrijd tot eerste",
               "Wat het ijs zeven maanden lang niet gaf, en hoe je dat in de zomer terughaalt",
               "Wanneer je het ijs weer op gaat en hoe de on-ice opbouwramp loopt",
               "Of aankomen in jouw geval helpt of je acceleratie kost"],
        "en": ["What eighteen weeks look like, week by week, from last game to first",
               "What the ice did not give you for seven months, and how to restore it in summer",
               "When to get back on the ice and how the on-ice ramp-up runs",
               "Whether adding mass helps you or costs you acceleration"],
        "de": ["Wie achtzehn Wochen aussehen, Woche für Woche, vom letzten Spiel bis zum ersten",
               "Was das Eis sieben Monate lang nicht gab — und wie du es im Sommer zurückholst",
               "Wann du zurück aufs Eis gehst und wie die On-Ice-Aufbaurampe verläuft",
               "Ob Zunehmen dir hilft oder deine Beschleunigung kostet"]},
 contents={"nl": ["Deel I — De zomer plannen: achttien weken, de audit, prioriteren, massa",
                  "Deel II — Off-ice bouwen: wat het ijs niet gaf, heup en lies, conditie, sprinten",
                  "Deel III — Terug op het ijs: opbouwramp, trainingskamp, oefenwedstrijden, laatste twee weken",
                  "Deel IV — Positieaccenten, jeugd en terugkeer na blessure",
                  "Bonusmodules: het 18-weken model week voor week, het 10-weken model, heup- en liesprogramma"],
           "en": ["Part I — Planning the summer: eighteen weeks, the audit, prioritising, mass",
                  "Part II — Building off-ice: what the ice did not give, hip and groin, conditioning, sprinting",
                  "Part III — Back on the ice: ramp-up, camp, friendlies, the last two weeks",
                  "Part IV — Positional accents, youth and return after injury",
                  "Bonus modules: the 18-week model week by week, the 10-week model, hip and groin programme"],
           "de": ["Teil I — Den Sommer planen: achtzehn Wochen, das Audit, Priorisieren, Masse",
                  "Teil II — Off-Ice aufbauen: was das Eis nicht gab, Hüfte und Leiste, Kondition, Sprints",
                  "Teil III — Zurück aufs Eis: Aufbaurampe, Trainingslager, Testspiele, die letzten zwei Wochen",
                  "Teil IV — Positionsakzente, Jugend und Rückkehr nach Verletzung",
                  "Bonusmodule: das 18-Wochen-Modell Woche für Woche, das 10-Wochen-Modell, Hüft- und Leistenprogramm"]},
 teaserQuote={"nl": "April tot september. Daarna beheer je zeven maanden lang wat je in die achttien weken hebt gebouwd.",
              "en": "April to September. After that you spend seven months managing what those eighteen weeks built.",
              "de": "April bis September. Danach verwaltest du sieben Monate lang, was diese achtzehn Wochen gebaut haben."}),
]

CORE_SPORTS = ["all", "icehockey", "football", "handball"]
PRO_SPORTS = ["icehockey"]
CORE_LEVEL = ["recreational", "competitive"]
PRO_LEVEL = ["competitive", "semi-pro", "pro"]


def sample_path(book_id):
    """
    Geeft het webpad van het inkijkexemplaar als dat bestand bestaat, anders None.
    Zo verschijnt de inkijkknop pas als er echt een PDF staat en geeft hij nooit
    een 404. Inkijkexemplaren maak je met tools/make_samples.py.
    """
    rel = "assets/samples/%s-inkijk.pdf" % book_id
    return "/" + rel if os.path.exists(os.path.join(ROOT, rel)) else None


def build_items():
    by_family = {}
    for b in BOOKS:
        by_family.setdefault(b["family"], {})[b["version"]] = b["id"]

    items = []
    for b in BOOKS:
        core = b["version"] == "core"
        it = {
            "id": b["id"],
            "family": b["family"],
            "version": b["version"],
            "sports": CORE_SPORTS if core else PRO_SPORTS,
            "category": b["category"],
            "phase": b["phase"],
            "level": CORE_LEVEL if core else PRO_LEVEL,
            "price": PRICE_CORE if core else PRICE_PRO,
            "compareAt": None,
            "status": "available",
            "pages": b["pages"],
            "weeks": b["weeks"],
            "languages": ["nl"],
            # Automatisch gevuld zodra assets/samples/<id>-inkijk.pdf bestaat.
            "sample": sample_path(b["id"]),
            "cover": None,
            "recommendFor": b["recommendFor"],
            "badges": b["badges"],
            "title": b["title"],
            "tagline": b["tagline"],
            "summary": b["summary"],
            "audience": b["audience"],
            "learn": b["learn"],
            "contents": b["contents"],
            "teaserQuote": b["teaserQuote"],
            "featured": b["featured"],
        }
        if core:
            it["proVariant"] = by_family[b["family"]].get("pro")
        else:
            it["coreVariant"] = by_family[b["family"]].get("core")
        items.append(it)
    return items


RULES = [
    dict(id="r-injury", when=[{"field": "injury", "in": ["yes"]}],
         handbook="strength-foundations-core", weight=130, blocksPrimaryOthers=True,
         reason={"nl": "Je gaf aan dat je in de afgelopen zes maanden geblesseerd was. Begin dan bij belastbaarheid en een gecontroleerde opbouw, niet bij een snelheids- of explosiviteitsblok. Bespreek de opbouw met je fysiotherapeut, of plan een Performance Check.",
                 "en": "You indicated an injury in the past six months. Start with load tolerance and controlled progression, not with a speed or power block. Discuss the build-up with your physiotherapist, or book a Performance Check.",
                 "de": "Du hast eine Verletzung in den letzten sechs Monaten angegeben. Beginne mit Belastbarkeit und kontrolliertem Aufbau, nicht mit einem Schnelligkeits- oder Explosivblock. Besprich den Aufbau mit deinem Physiotherapeuten oder buche einen Performance Check."}),
    dict(id="r-asymmetry", when=[{"field": "asymmetry", "in": ["yes"]}],
         handbook="strength-foundations-core", weight=70,
         reason={"nl": "Je merkt duidelijk verschil tussen links en rechts. Unilateraal werk en symmetrie eerst; anders bouw je het verschil mee op.",
                 "en": "You notice a clear left–right difference. Unilateral work and symmetry first, otherwise you build the difference in.",
                 "de": "Du merkst einen klaren Links-Rechts-Unterschied. Erst unilaterale Arbeit und Symmetrie, sonst baust du den Unterschied mit auf."}),
    dict(id="r-strength-below", when=[{"domain": "strength", "is": "below"}],
         handbook="strength-foundations-core", weight=100,
         reason={"nl": "Je maximale kracht ligt onder de referentiewaarde. Zolang dat zo is, is elk snelheidsblok bouwen op zand.",
                 "en": "Your maximal strength sits below the reference range. Until that changes, any speed block is built on sand.",
                 "de": "Deine Maximalkraft liegt unter dem Referenzbereich. Solange das so ist, baut jeder Schnelligkeitsblock auf Sand."}),
    dict(id="r-elastic-below", when=[{"domain": "elastic", "is": "below"}],
         handbook="power-foundations-core", weight=80,
         reason={"nl": "Je sprongkracht blijft achter. Dat is een explosiviteitsvraagstuk: hoeveel kracht je kwijt kunt in de tijd die je hebt.",
                 "en": "Your jump output lags. That is a power question: how much force you can express in the time available.",
                 "de": "Deine Sprungkraft hinkt nach. Das ist eine Explosivitätsfrage: wie viel Kraft du in der verfügbaren Zeit abrufst."}),
    dict(id="r-rfd-below", when=[{"domain": "rfd", "is": "below"}],
         handbook="power-foundations-core", weight=90,
         reason={"nl": "Je bouwt kracht te langzaam op voor de tijdvensters van je sport. Dat is precies waar rate of force development over gaat.",
                 "en": "You build force too slowly for the time windows your sport gives you. That is exactly what rate of force development is about.",
                 "de": "Du baust Kraft zu langsam auf für die Zeitfenster deiner Sportart. Genau darum geht es bei der Rate of Force Development."}),
    dict(id="r-elastic-below-strong-base",
         when=[{"domain": "elastic", "is": "below"}, {"domain": "strength", "isNot": "below"}],
         handbook="power-foundations-core", weight=95,
         reason={"nl": "Je bent sterk genoeg, maar je krijgt die kracht niet snel genoeg op de grond. Dat is een omzettingsprobleem, geen krachtprobleem.",
                 "en": "You are strong enough, but you cannot put that force into the ground fast enough. That is a conversion problem, not a strength problem.",
                 "de": "Du bist stark genug, bringst die Kraft aber nicht schnell genug auf den Boden. Das ist ein Umsetzungs-, kein Kraftproblem."}),
    dict(id="r-accel-below", when=[{"domain": "accel", "is": "below"}],
         handbook="speed-foundations-core", weight=85,
         reason={"nl": "Je eerste meters kosten je tijd. Acceleratie is een aparte vaardigheid met een eigen techniek en een eigen opbouw.",
                 "en": "Your first metres cost you time. Acceleration is a separate skill with its own technique and progression.",
                 "de": "Deine ersten Meter kosten dich Zeit. Beschleunigung ist eine eigene Fähigkeit mit eigener Technik und eigenem Aufbau."}),
    dict(id="r-topspeed-below",
         when=[{"domain": "topspeed", "is": "below"}, {"domain": "accel", "isNot": "below"}],
         handbook="speed-foundations-core", weight=65,
         reason={"nl": "Je komt goed weg maar loopt niet door. Topsnelheid telt ook als je hem in je sport zelden haalt: hij bepaalt je snelheidsreserve.",
                 "en": "You start well but do not carry on. Top speed matters even if your sport rarely lets you reach it: it sets your speed reserve.",
                 "de": "Du startest gut, läufst aber nicht durch. Höchstgeschwindigkeit zählt auch, wenn du sie selten erreichst: Sie bestimmt deine Reserve."}),
    dict(id="r-cod-below", when=[{"domain": "cod", "is": "below"}],
         handbook="agility-foundations-core", weight=90,
         reason={"nl": "Je verliest tijd bij het van richting veranderen. Dat begint bijna altijd bij afremmen, niet bij het versnellen erna.",
                 "en": "You lose time changing direction. That almost always starts with braking, not with the acceleration afterwards.",
                 "de": "Du verlierst Zeit beim Richtungswechsel. Das beginnt fast immer beim Abbremsen, nicht beim Beschleunigen danach."}),
    dict(id="r-engine-below", when=[{"domain": "engine", "is": "below"}],
         handbook="preseason-foundations-core", weight=88,
         reason={"nl": "Je herstel tussen inspanningen blijft achter. Die basis leg je in de voorbereiding, niet halverwege het seizoen.",
                 "en": "Your recovery between efforts lags. That base is built in pre-season, not halfway through the year.",
                 "de": "Deine Erholung zwischen Belastungen hinkt nach. Diese Basis legst du in der Vorbereitung, nicht mitten in der Saison."}),
    dict(id="r-preseason-phase", when=[{"field": "phase", "in": ["pre-season"]}],
         handbook="preseason-foundations-core", weight=92,
         reason={"nl": "Je zit in de voorbereiding. Dit is de enige aaneengesloten periode waarin ontwikkeling het hoofddoel mag zijn — die moet je plannen.",
                 "en": "You are in pre-season. This is the only uninterrupted period where development can be the main goal — it needs planning.",
                 "de": "Du bist in der Vorbereitung. Das ist die einzige zusammenhängende Phase, in der Entwicklung Hauptziel sein darf — sie muss geplant werden."}),
    dict(id="r-hockey-preseason",
         when=[{"field": "sport", "in": ["icehockey"]}, {"field": "phase", "in": ["pre-season"]}],
         handbook="preseason-foundations-pro", weight=105,
         reason={"nl": "IJshockey in de voorbereiding: achttien weken tussen de laatste wedstrijd en de eerste, met een eigen opbouw terug naar het ijs.",
                 "en": "Ice hockey in pre-season: eighteen weeks between the last game and the first, with its own ramp back onto the ice.",
                 "de": "Eishockey in der Vorbereitung: achtzehn Wochen zwischen letztem und erstem Spiel, mit eigener Rampe zurück aufs Eis."}),
    dict(id="r-hockey-cod",
         when=[{"field": "sport", "in": ["icehockey"]}, {"domain": "cod", "is": "below"}],
         handbook="agility-foundations-pro", weight=75,
         reason={"nl": "Richting veranderen op ijs is een ander probleem dan op gras: het draait om edges, stops en transitions.",
                 "en": "Changing direction on ice is a different problem than on grass: it comes down to edges, stops and transitions.",
                 "de": "Richtungswechsel auf Eis ist ein anderes Problem als auf Rasen: Es geht um Edges, Stops und Transitions."}),
    dict(id="r-in-season", when=[{"field": "phase", "in": ["season"]}],
         handbook="season-foundations-core", weight=85,
         reason={"nl": "Je zit midden in het seizoen. Dan gaat het niet om ontwikkelen maar om niet inzakken, en dat vraagt sturing op belasting.",
                 "en": "You are mid-season. The goal is not development but avoiding decline, and that requires steering load.",
                 "de": "Du bist mitten in der Saison. Es geht nicht um Entwicklung, sondern darum, nicht einzubrechen — das erfordert Belastungssteuerung."}),
    dict(id="r-hockey-in-season",
         when=[{"field": "sport", "in": ["icehockey"]}, {"field": "phase", "in": ["season"]}],
         handbook="season-foundations-pro", weight=100,
         reason={"nl": "Een ijshockeyseizoen is een belastingsprobleem: twee wedstrijden per week, veel ijs en veel reistijd.",
                 "en": "An ice hockey season is a load problem: two games a week, a lot of ice and a lot of travel.",
                 "de": "Eine Eishockeysaison ist ein Belastungsproblem: zwei Spiele pro Woche, viel Eis und viel Reisezeit."}),
    dict(id="r-no-weakness", when=[{"weakDomains": 0}],
         handbook="agility-foundations-core", weight=50,
         reason={"nl": "Geen van je waarden valt onder de referentie. Dan zit de winst meestal in de kwaliteit die zelden getraind wordt: afremmen en reageren.",
                 "en": "None of your values fall below reference. The gain then usually sits in the quality nobody trains: braking and reacting.",
                 "de": "Keiner deiner Werte liegt unter dem Referenzbereich. Der Gewinn liegt dann meist in der Qualität, die kaum jemand trainiert: Bremsen und Reagieren."}),
]


def main():
    items = build_items()
    hb = {
        "_readme": ("Twaalf handboeken: zes families (Power, Strength, Speed, Agility, Season, Pre-Season) "
                    "in Core en Pro Edition. Paginaaantallen en hoofdstukindeling komen uit de PDF's zelf. "
                    "Gegenereerd door tools/make_handbooks.py — pas daar aan, niet hier. "
                    "'sample' wordt automatisch gevuld voor elk handboek waarvoor "
                    "assets/samples/<id>-inkijk.pdf bestaat; anders blijft het null en "
                    "verschijnt de inkijkknop niet. Maak die PDF's met tools/make_samples.py."),
        "currency": "EUR",
        "families": FAMILIES,
        "items": items,
    }
    with open(os.path.join(ROOT, "assets/data/handbooks.json"), "w", encoding="utf-8") as f:
        json.dump(hb, f, ensure_ascii=False, indent=1)

    rules = {
        "_readme": ("Aanbevelingslogica voor de zelftest. Alle regels worden geëvalueerd; elke match telt "
                    "zijn 'weight' op bij het betreffende handboek. Het hoogste totaal wordt de primaire "
                    "aanbeveling. Verwijst een regel naar een handboek dat niet in handbooks.json staat, "
                    "dan wordt de regel stilzwijgend overgeslagen. Gegenereerd door tools/make_handbooks.py."),
        "proUpgrade": {
            "_readme": "Bij deze sport en niveaus krijgt de Pro-versie voorrang boven de Core, mits die bestaat.",
            "sports": ["icehockey"],
            "levels": ["semi-pro", "pro"],
            "alsoWhenWeakDomains": 3,
        },
        "rules": RULES,
    }
    with open(os.path.join(ROOT, "assets/data/rules.json"), "w", encoding="utf-8") as f:
        json.dump(rules, f, ensure_ascii=False, indent=1)

    print("handbooks.json: %d handboeken" % len(items))
    print("rules.json:     %d regels" % len(RULES))
    ids = {i["id"] for i in items}
    weesjes = sorted({r["handbook"] for r in RULES} - ids)
    print("regels zonder bestaand handboek:", weesjes or "geen")


if __name__ == "__main__":
    main()
